INSERT INTO otp

(
-- Time Period
"year",
"quarter",
"month",
"dayofmonth",
"dayofweek",
"flightdate",
-- Airline
"uniquecarrier",
"airlineid",
"carrier",
"tailnum",
"flightnum",
-- Origin
"originairportid",
"originairportseqid",
"origincitymarketid",
"origin",
"origincityname",
"originstate",
"originstatefips",
"originstatename",
"originwac",
-- Destination
"destairportid",
"destairportseqid",
"destcitymarketid",
"dest",
"destcityname",
"deststate",
"deststatefips",
"deststatename",
"destwac",
-- Departure Performance
"crsdeptime",
"deptime",
"depdelay",
"depdelayminutes",
"depdel15",
"departuredelaygroups",
"deptimeblk",
"taxiout",
"wheelsoff",
-- Arrival Performance
"wheelson",
"taxiin",
"crsarrtime",
"arrtime",
"arrdelay",
"arrdelayminutes",
"arrdel15",
"arrivaldelaygroups",
"arrtimeblk",
-- Cancellations and Diversions
"cancelled",
"cancellationcode",
"diverted",
-- Flight Summaries
"crselapsedtime",
"actualelapsedtime",
"airtime",
"flights",
"distance",
"distancegroup",
-- Cause of Delay (Data starts 6/2003)
"carrierdelay",
"weatherdelay",
"nasdelay",
"securitydelay",
"lateaircraftdelay",
-- Gate Return Information at Origin Airport (Data starts 10/2008)
"firstdeptime",
"totaladdgtime",
"longestaddgtime",
-- Diverted Airport Information (Data starts 10/2008)
"divairportlandings",
"divreacheddest",
"divactualelapsedtime",
"divarrdelay",
"divdistance",
"div1airport",
"div1airportid",
"div1airportseqid",
"div1wheelson",
"div1totalgtime",
"div1longestgtime",
"div1wheelsoff",
"div1tailnum",
"div2airport",
"div2airportid",
"div2airportseqid",
"div2wheelson",
"div2totalgtime",
"div2longestgtime",
"div2wheelsoff",
"div2tailnum",
"div3airport",
"div3airportid",
"div3airportseqid",
"div3wheelson",
"div3totalgtime",
"div3longestgtime",
"div3wheelsoff",
"div3tailnum",
"div4airport",
"div4airportid",
"div4airportseqid",
"div4wheelson",
"div4totalgtime",
"div4longestgtime",
"div4wheelsoff",
"div4tailnum",
"div5airport",
"div5airportid",
"div5airportseqid",
"div5wheelson",
"div5totalgtime",
"div5longestgtime",
"div5wheelsoff",
"div5tailnum"
)


SELECT


-- Time Period
"year",
"quarter",
"month",
"dayofmonth",
"dayofweek",
"flightdate",
-- Airline
"uniquecarrier",
"airlineid",
"carrier",
"tailnum",
"flightnum",
-- Origin
"originairportid",
"originairportseqid",
"origincitymarketid",
"origin",
"origincityname",
"originstate",
"originstatefips",
"originstatename",
"originwac",
-- Destination
"destairportid",
"destairportseqid",
"destcitymarketid",
"dest",
"destcityname",
"deststate",
"deststatefips",
"deststatename",
"destwac",
-- Departure Performance
CASE WHEN "crsdeptime" IS NULL OR LENGTH("crsdeptime") = 0 THEN NULL ELSE "crsdeptime"::TIME END,
CASE WHEN "deptime" IS NULL OR LENGTH("deptime") = 0 THEN NULL ELSE "deptime"::TIME END,
"depdelay"::NUMERIC::INTEGER,
"depdelayminutes"::NUMERIC::INTEGER,
CASE WHEN "depdel15" IS NULL THEN false ELSE "depdel15"::NUMERIC::INTEGER::BOOLEAN END,
CASE WHEN "departuredelaygroups" IS NULL THEN 0 ELSE "departuredelaygroups"::NUMERIC::SMALLINT END,
"deptimeblk",
"taxiout"::NUMERIC::INTEGER,
CASE WHEN "wheelsoff" IS NULL OR LENGTH("wheelsoff") = 0 THEN NULL ELSE "wheelsoff"::TIME END,
-- Arrival Performance
CASE WHEN "wheelson" IS NULL OR LENGTH("wheelson") = 0 THEN NULL ELSE "wheelson"::TIME END,
"taxiin"::NUMERIC::INTEGER,
CASE WHEN "crsarrtime" IS NULL OR LENGTH("crsarrtime") = 0 THEN NULL ELSE "crsarrtime"::TIME END,
CASE WHEN "arrtime" IS NULL OR LENGTH("arrtime") = 0 THEN NULL ELSE "arrtime"::TIME END,
"arrdelay"::NUMERIC::INTEGER,
"arrdelayminutes"::NUMERIC::INTEGER,
CASE WHEN "arrdel15" IS NULL THEN false ELSE "arrdel15"::NUMERIC::INTEGER::BOOLEAN END,
CASE WHEN "arrivaldelaygroups" IS NULL THEN 0 ELSE "arrivaldelaygroups"::NUMERIC::SMALLINT END,
"arrtimeblk",
-- Cancellations and Diversions
"cancelled"::NUMERIC::INTEGER::BOOLEAN,
CASE WHEN "cancellationcode" IS NULL OR LENGTH("cancellationcode") = 0 THEN NULL ELSE "cancellationcode" END,
"diverted"::NUMERIC::INTEGER::BOOLEAN,
-- Flight Summaries
"crselapsedtime"::NUMERIC::INTEGER,
"actualelapsedtime"::NUMERIC::INTEGER,
"airtime"::NUMERIC::INTEGER,
"flights"::NUMERIC::SMALLINT,
"distance"::NUMERIC::INTEGER,
"distancegroup",
-- Cause of Delay (Data starts 6/2003)
"carrierdelay"::NUMERIC::SMALLINT,
"weatherdelay"::NUMERIC::SMALLINT,
"nasdelay"::NUMERIC::SMALLINT,
"securitydelay"::NUMERIC::SMALLINT,
"lateaircraftdelay"::NUMERIC::SMALLINT,
-- Gate Return Information at Origin Airport (Data starts 10/2008)
CASE WHEN "firstdeptime" IS NULL OR LENGTH("firstdeptime") = 0 THEN NULL ELSE "firstdeptime"::TIME END,
"totaladdgtime"::NUMERIC::SMALLINT,
"longestaddgtime"::NUMERIC::SMALLINT,
-- Diverted Airport Information (Data starts 10/2008)
"divairportlandings",
CASE WHEN "divreacheddest" IS NULL THEN true ELSE "divreacheddest"::NUMERIC::INTEGER::BOOLEAN END,
"divactualelapsedtime"::NUMERIC::INTEGER,
"divarrdelay"::NUMERIC::INTEGER,
"divdistance"::NUMERIC::INTEGER,
"div1airport",
"div1airportid",
"div1airportseqid",
CASE WHEN "div1wheelson" IS NULL OR LENGTH("div1wheelson") = 0 THEN NULL ELSE "div1wheelson"::TIME END,
"div1totalgtime"::NUMERIC::INTEGER,
"div1longestgtime"::NUMERIC::INTEGER,
CASE WHEN "div1wheelsoff" IS NULL OR LENGTH("div1wheelsoff") = 0 THEN NULL ELSE "div1wheelsoff"::TIME END,
"div1tailnum",
"div2airport",
"div2airportid",
"div2airportseqid",
CASE WHEN "div2wheelson" IS NULL OR LENGTH("div2wheelson") = 0 THEN NULL ELSE "div2wheelson"::TIME END,
"div2totalgtime"::NUMERIC::INTEGER,
"div2longestgtime"::NUMERIC::INTEGER,
CASE WHEN "div2wheelsoff" IS NULL OR LENGTH("div2wheelsoff") = 0 THEN NULL ELSE "div2wheelsoff"::TIME END,
"div2tailnum",
"div3airport",
"div3airportid",
"div3airportseqid",
CASE WHEN "div3wheelson" IS NULL OR LENGTH("div3wheelson") = 0 THEN NULL ELSE "div3wheelson"::TIME END,
"div3totalgtime"::NUMERIC::INTEGER,
"div3longestgtime"::NUMERIC::INTEGER,
CASE WHEN "div3wheelsoff" IS NULL OR LENGTH("div3wheelsoff") = 0 THEN NULL ELSE "div3wheelsoff"::TIME END,
"div3tailnum",
"div4airport",
"div4airportid",
"div4airportseqid",
CASE WHEN "div4wheelson" IS NULL OR LENGTH("div4wheelson") = 0 THEN NULL ELSE "div4wheelson"::TIME END,
"div4totalgtime"::NUMERIC::INTEGER,
"div4longestgtime"::NUMERIC::INTEGER,
CASE WHEN "div4wheelsoff" IS NULL OR LENGTH("div4wheelsoff") = 0 THEN NULL ELSE "div4wheelsoff"::TIME END,
"div4tailnum",
"div5airport",
"div5airportid",
"div5airportseqid",
CASE WHEN "div5wheelson" IS NULL OR LENGTH("div5wheelson") = 0 THEN NULL ELSE "div5wheelson"::TIME END,
"div5totalgtime"::NUMERIC::INTEGER,
"div5longestgtime"::NUMERIC::INTEGER,
CASE WHEN "div5wheelsoff" IS NULL OR LENGTH("div5wheelsoff") = 0 THEN NULL ELSE "div5wheelsoff"::TIME END,
"div5tailnum"


FROM otp_staging;


